<a href="https://colab.research.google.com/github/Cherberushka/BOT_YT/blob/master/HW_ML%2BPython%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# План:
1. Pytho
2. Numpy
3. Pandas
4. Regexp + regexp with dataframes
5. Texts
6. Matplotlib, Seaborn
7. Classification, clustering, binary, multiclass, multilabel
8. Metrics
9. Feature extraction
10. Pyspark/sql
Смотри, Максим, это не локальная копия

<img src="gifs/start.gif" width="400">

# Python

* Целая куча упражнений на типы данных\операторы и функции

https://www.w3resource.com/python-exercises/

Типы данных:
    * Числа (7382, 3.14, 3+4j, Decimal, Fraction)
    * Строки ('net', "your's", u'радость')
    * Списки ([1, [2, 'three'], 4])
    * Словари ({'Alex': 2, 'Brian': 4})
    * Кортежи ('Leo', 21.7, 'single')
    * Множества (set(1,2,3), {'a', 'b', 'c'})
    * Файлы (open('myfile', 'r'))

1. Склеить 3 подстроки "ada", "lovelace", "was considered the world's first computer programmer.". Первые две строки сделать с большой буквы.  (★☆☆)


In [ ]:
a = "ada"
b = "lovelace"
c = "was considered the world's first computer programmer."
print(a.capitalize() + b.capitalize() + c)

AdaLovelacewas considered the world's first computer programmer.


2. Удаление лишних пробельных символов справа, слева, с обоих сторон  (☆☆☆)

In [ ]:
a = "      ada     "
print(a.strip())

ada


3. Найти первое вхождение в строку подстроки (☆☆☆)

In [ ]:
s1="But if you stick with me, I’m gonna accomplish great things, Morty, and you’re gonna be part of ’em."
s2="you"

##your code
print(s1.find(s2))

7


* isdigit - состоит ли строка из цифр;
* isalpha - состоит ли строка из букв;
* isalnum - состоит ли строка из цифр или букв;
* islower - состоит ли строка из символов в нижнем регистре;
* isupper - состоит ли строка из символов в верхнем регистре;
* istitle - начинаются ли слова в строке с заглавной буквы.

4. Разбить строку по разделителю (☆☆☆)

In [ ]:
s1="Holy#cow,#Rick!#I#didn’t#know#hanging#out#with#you#was#making#me#smarter!"
##your code
list = s1.split('#')
print(list)

['Holy', 'cow,', 'Rick!', 'I', 'didn’t', 'know', 'hanging', 'out', 'with', 'you', 'was', 'making', 'me', 'smarter!']


5. Полученный массив строк склеить через пробел (★☆☆)

In [ ]:
s1 = ' '.join(list)
print(s1)

Holy cow, Rick! I didn’t know hanging out with you was making me smarter!


6. Вывести данные из словаря в три строки в виде "NAME (age AGE) is a JOB" (★☆☆)

(hint: .format())

In [ ]:
personal_data = {1: ("Ann", 29, "Artist"), 
               2: ("Leo", 54, "Programmer"), 
               3: ("Tiffany", 43, "Shop Assistant")}
##your code
for i in range(1, len(personal_data) + 1):
  print(f'{personal_data[i][0]} (age {personal_data[i][1]}) is a {personal_data[i][2]}')
print('\n')
for i in range(1, len(personal_data) + 1):
  print('{} (age {}) is a {}'.format(personal_data[i][0], personal_data[i][1], personal_data[i][2]))

Ann (age 29) is a Artist
Leo (age 54) is a Programmer
Tiffany (age 43) is a Shop Assistant


Ann (age 29) is a Artist
Leo (age 54) is a Programmer
Tiffany (age 43) is a Shop Assistant


7. Требуется определить, является ли данный год високосным. (год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.)  (★★☆)

Входные данные: Вводится единственное число - номер года (целое, положительное, не превышает 30000).

Выходные данные: Требуется вывести слово YES, если год является високосным и NO - в противном случае.

In [ ]:
year = int(input()) 
if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:
  print("YES")
else:
  print("NO")

8. Закодируйте каждый элемент списка слов числом, результат сопоставления (слово-число) поместите в словарь.  (★☆☆)

In [ ]:
words = ['Not', 'my', 'cup', 'of', 'tea']
##your code
keys = ['0', '1', '2', '3', '4']
dict_w = dict(zip(keys, words))
print(dict_w)

9. Удалить второй элемент из списка по индексу\по значению  (★☆☆)

In [ ]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']

##your code
del dogs[1]
print(dogs)
dogs.remove('labrador retriever')
print(dogs)

10. Вывести срез списка с 3 по 5 элемент включительно и все слова перевести в верхний регистр (★☆☆)

In [ ]:
dogs = ['border', 'collie', 'australian', 'cattle', 'dog', 'labrador', 'retriever']
##your code
print(dogs[3:6:])
for i in dogs:
  dogs[dogs.index(i)] = i.upper()
print(dogs)
print(dogs[3:6:])

11. Словарь словарей. Вывести из словаря для каждого питомца его имя, породу, имя владельца, и наличие прививки. Строку вывода формировать через .format() (★☆☆)

In [ ]:
pets = {'willie': {'kind': 'dog', 'owner': 'eric', 'vaccinated': True},
        'walter': {'kind': 'cockroach', 'owner': 'eric', 'vaccinated': False},
        'peso': {'kind': 'dog', 'owner': 'chloe', 'vaccinated': True},
        }
        
##your code
for i in pets:
  print('Имя питомца {}; Порода: {}; Владелец: {}; Привит: {}'.format(i, pets[i]['kind'], pets[i]['owner'], pets[i]['vaccinated']))


12. Проверить является ли множество подмножеством другого множества  (★☆☆)

In [ ]:
a=set([2, 5, 6])
b=set([2, 4, 8, 3, 5, 6])

##your code
print(a)

13. Объединить несколько множеств (★☆☆)

In [ ]:
set_a=set([10, 35, 6, 5])
set_b=set([2, 4, 8, 3, 5, 6, 35])
set_c=set([4, 5, 35])

##your code
d = set_a.union(set_b).union(set_c)
print(d)

14. Посчитать пересечение множества b с остальными из предыдущего задания  (★★☆)

(hint: set.intersection(other, ...) (или set & other &) )

In [ ]:
print(set_b.intersection(set_a))
print(set_b.intersection(set_c))
print(set_b.intersection(set_a, set_c))

15. Вывести множество из элементов, встречающихся в одном множестве, но не встречающиеся в обоих. (★★☆)

(hint: .symmetric_difference())

In [ ]:
a=set([1, 2, 3, 4, 5])
b=set([3, 4, 5, 6, 7])

##your code
print(a.symmetric_difference(b))

16. Предположим, есть файл с данными клиентов. В качестве простого примера воьзьмем txt-файл(нужно создать файл с предложенным/другим содержанием самостоятельно) следующего содержания:

    lastname,age,debt,occupation
    
    Adrianov,25,30000,artist
    
    Нужно считать файл data/credit_sample.txt.
    Сделать словарь вида:
        {lastname: (age,debt,occupation)}
    
    Посчитать сколько уникальных профессий получилось в словаре.
    
    Результат записать в json (★★★)

### os, sys, datetime

In [ ]:
import os
import sys
import datetime

17. Получить список файлов в папке gifs/ и оставить только файлы с расширением .gif (★★☆)

Текущая деректория: /content


18. Создать папку с названием temp и удалить её (★☆☆)

In [ ]:
os.chdir('/content')  # сменить директорию
print("Текущая деректория:", os.getcwd())

os.mkdir("temp")  # создание директории(папки)

print("Все папки и файлы после создания temp:", os.listdir())  # вывести список файлов и папок в текущей директории

os.rmdir("temp")  # удаление директории(папки)
print("Все папки и файлы после удаления temp:", os.listdir())  # вывести список файлов и папок в текущей директории

Текущая деректория: /content
Все папки и файлы после создания temp: ['.config', 'temp', 'sample_data']
Все папки и файлы после удаления temp: ['.config', 'sample_data']


19. Вывести переменные среды (★☆☆)

(hint: environ)

In [ ]:
for key in os.environ:
    print(key, '=>', os.environ[key])

NV_LIBCUBLAS_DEV_VERSION => 11.4.1.1043-1
NV_CUDA_COMPAT_PACKAGE => cuda-compat-11-2
NV_CUDNN_PACKAGE_DEV => libcudnn8-dev=8.1.1.33-1+cuda11.2
LD_LIBRARY_PATH => /usr/local/nvidia/lib:/usr/local/nvidia/lib64
NV_LIBNCCL_DEV_PACKAGE => libnccl-dev=2.8.4-1+cuda11.2
TCLLIBPATH => /usr/share/tcltk/tcllib1.19
CLOUDSDK_PYTHON => python3
LANG => en_US.UTF-8
NV_LIBNPP_DEV_PACKAGE => libnpp-dev-11-2=11.3.2.152-1
HOSTNAME => 72cb702d1d3a
OLDPWD => /
CLOUDSDK_CONFIG => /content/.config
NV_LIBNPP_VERSION => 11.3.2.152-1
NV_NVPROF_DEV_PACKAGE => cuda-nvprof-11-2=11.2.152-1
NVIDIA_VISIBLE_DEVICES => all
NV_NVPROF_VERSION => 11.2.152-1
NV_LIBCUSPARSE_VERSION => 11.4.1.1152-1
DATALAB_SETTINGS_OVERRIDES => {"kernelManagerProxyPort":6000,"kernelManagerProxyHost":"172.28.0.13","jupyterArgs":["--ip=172.28.0.12","--transport=ipc"],"debugAdapterMultiplexerPath":"/usr/local/bin/dap_multiplexer","enableLsp":true}
NV_LIBCUBLAS_DEV_PACKAGE => libcublas-dev-11-2=11.4.1.1043-1
ENV => /root/.bashrc
NCCL_VERSION => 

20. Как игнорировать warrnings?

In [ ]:
import warnings
warnings.filterwarnings("ignore")

* Про datetime и timedelta 

https://www.guru99.com/date-time-and-datetime-classes-in-python.html

In [ ]:
import datetime
from datetime import date
from datetime import time
from datetime import datetime, timedelta

21. Вывести сегодняшнюю, вчерашнюю и завтрашнюю дату (☆☆☆)

In [ ]:
today = datetime.now() 
yesterday = today - timedelta(1)
tomorrow = today + timedelta(1)

print("Вчера было: ", yesterday.strftime('%d-%m-%Y'))
print("Сегодня: ", today.strftime('%d-%m-%Y'))
print("Завтра будет: ", tomorrow.strftime('%d-%m-%Y'))

Вчера было:  05-11-2022
Сегодня:  06-11-2022
Завтра будет:  07-11-2022


22. Вывести день недели сегодняшней даты (★☆☆)

In [ ]:
week_day = 'Monday Tuesday Wednesday Thursday Friday Saturday Sunday'.split()
print(week_day[today.weekday()])

Sunday


23. Получить список дат за предыдущую неделю (★★☆)

24. Вывести дату с часами и минутами, отформатировать в формате: 01.12.2019 00:12:54 (★★☆)
            
(hint: now().strftime())

In [ ]:
t = datetime.time(datetime.now())
tt = datetime.now().strftime('%d.%m.%Y %H:%M:%S')
print(tt)

06.11.2022 12:54:09


25. Исходя из текущей даты вычислить дату предыдущего понедельника (★★★)

In [108]:
### ПЕРЕДЕЛАТЬ
td = yesterday.weekday()
count = 0
if td == 0:
  print((today - timedelta(6)).strftime('%d-%m-%Y'))
else:
  while td != 0:
    td -= 1
    count += 1
  print((today - timedelta(count)).strftime('%d-%m-%Y'))

01-11-2022


# Numpy

### numpy в картинках (реально лучший):

https://jalammar.github.io/visual-numpy/

In [217]:
import numpy as np

1. Задать нулевой вектор размером 10 (★☆☆)

(hint: np.zeros)

In [216]:
vec = np.zeros(10, dtype=np.integer)
print(vec)

[0 0 0 0 0 0 0 0 0 0]


2. Как найти размер занимаемой памяти любым массивом (★☆☆)

(hint: size, itemsize)

In [215]:
a = np.array([[10,20],[30,40]], dtype=np.float64)
print(a.itemsize)
print(a.__sizeof__())
print(sys.getsizeof(a))
##

8
152
152


3. Создать вектор из 10 нулей, кроме пятого элемента, который равен 1 (★☆☆)

In [214]:
vec3_1 = (np.arange(10) == 4).astype(int)
print(vec3_1)

#

vec3_2 = np.zeros(10, dtype=np.integer)
vec3_2[4] = 1
print(vec3_2)

[0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


4. Создать вектор от 10 до 50 включительно (★☆☆)

(hint:np.arange)

In [212]:
print(*np.arange(10,50, dtype=np.integer))

10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49


5. Перевернуть вектор (первый элемент будет последним) (★☆☆)

In [160]:
matrix5 = np.arange(1,10)
print(matrix5[::-1])

[9 8 7 6 5 4 3 2 1]


6. Создать матрицу 3х3 с элементами от 0 до 8 (★☆☆)

(hint: reshape)

In [167]:
matrix6 = np.arange(9).reshape(3,3)
print(matrix6)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Найти индексы не нулевых эемелентов в numpy array [1,2,0,0,4,0] (★☆☆)

(hint: np.nonzero)

In [170]:
matrix7 = np.array([1,2,0,0,4,0], dtype=np.integer)
print(*matrix7.nonzero())

[0 1 4]


8. Создать матрицу 10x10 array с рандомными числами и найти минимум, максимум и среднее (★☆☆)

In [178]:
matrix8 = np.random.random(100).reshape(10,10)
print(f'min = {matrix8.min()}', f'max = {matrix8.max()}', f'avg = {matrix8.mean()}', sep='\n')

min = 0.01908383554118076
max = 0.9914769184032853
avg = 0.538070235413826


9. Создать матрицу 8x8 и заполнить 0 и 1 в стиле шахматной доски (★☆☆)

(hint: array[::n])

In [191]:
matrix9 = np.zeros((8,8), dtype=np.integer)
matrix9[1::2,::2] = 1
matrix9[::2,1::2] = 1
print(matrix9)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


10. Нормализовать рандомную матрицу 5x5 (★☆☆)

(hint: (x - mean) / std)

In [205]:
matrix10 = np.random.random((5,5))
matrix10 = (matrix10 - matrix10.mean()) / matrix10.std()
print(matrix10)

[[-1.6133689  -1.17515038 -0.58440326  1.46421503 -0.57991875]
 [ 1.29228138  0.76930026  0.37225683 -1.46681621  0.26483338]
 [ 0.58859843  0.60427057 -0.26872083  1.43166013 -1.34013029]
 [ 0.29649307  0.98045721  0.95687181  0.84850496 -0.32050625]
 [-0.86574433  1.44251119 -0.77532788 -1.04357212 -1.27859504]]


11. Найти общие элементы между двумя массивами

(hint: np.intersect1d)

In [210]:
matrix11_a = np.arange(0,7, dtype=np.integer)
matrix11_b = np.arange(4,9, dtype=np.integer)
print(np.intersect1d(matrix11_a, matrix11_b))

[4 5 6]


12. Извлечь целую часть рандомного массива чисел различными способами (максимум 5) (★★☆)

13. Создать рандомный вектор размера 10 и отсортировать его (★★☆)

In [220]:
matrix13 = np.random.random(10)
matrix13.sort()
print(matrix13)

[0.12621793 0.13908878 0.19707993 0.21075708 0.64189502 0.67568719
 0.69331236 0.78187608 0.89246792 0.90930037]


14. Проверить одинаковы ли два рандомных массива А и B (★★☆)

(hint: np.allclose, np.array_equal)

In [228]:
m14_A = [1, 2, 3, 4, 5]
m14_B = [2, 5, 1, 4, 3]

m14_A.sort()
m14_B.sort()

print(np.array_equal (m14_A,m14_B))

True


15. Создать рандомный вектор размером 10 и максимальный элемент заменить на -1 (★★☆)

(hint: argmax)

16. Найдите самый близкий элемент к данному рандомному числу в векторе? (★★☆)

(hint: argmin)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index =  ???????
print(Z[index])

SyntaxError: ignored

17. Посчитать среднее для каждой строки матрицы (★★☆)

18. Посчитать среднее со скользящим окном над массивом (★★★)

(hint: np.cumsum)

<img src="gifs/bender.gif" width="400">

# Regular expressions

* Cупер статья на все времена. Особенно понятно все про такие сложные штуки как lookaround. 

https://habr.com/ru/post/349860/


* Задания на регулярки

https://regexone.com/

* На этом сайте удобно тестировать регулярку, которую мучаешь, можно написать несколько примеров и тестировать на них. Важно не забывать выбирать Python:

https://regex101.com/

1. Из строки в файле data/rejson.txt вытащить хэш. Пример:

'master_guid': '<b>233880bb4c50d247f84edc9cac9e6e29</b>_2308194320'

# Pandas

* Pandas в картинках

https://jalammar.github.io/gentle-visual-intro-to-data-analysis-python-pandas/

* 10 minutes to pandas

https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

* 🐼реально классный твиттер чувака с крутыми pandas tricks:
    
https://mobile.twitter.com/i/moments/1158828895547854849